### ISSUE TITLE
Community support

### ISSUE THREAD

**Issue by arbrandes** [openedx/wg-coordination#1]
Duties include:

* Assist with moderating [the forum](discuss.openedx.org/)
* Periodically answer questions in the forum or [on Slack](https://openedx.slack.com)

**Comment by antoviaque** [comment]
@nizarmah has also taken over your duties with this @arbrandes so I'm updating the assignee. We have other moderators and people doing community support though, so it might be worth linking to an authoritative list somewhere if we have one.

**Comment by antoviaque** [comment]
Duties for community support are tracked in other places now, so closing this ticket.
