### ISSUE TITLE
Debugging persistent grade issues

### ISSUE THREAD

**Issue by antoviaque** [openedx/wg-coordination#106]
Contributor meetup topic imported from https://openedx.atlassian.net/wiki/spaces/COMM/pages/3934289923/2023-11-28+CC+Working+Group+Meeting+Notes

<h4 id="Follow-up---Debugging-persistent-grade-issues" data-renderer-start-pos="197"><strong data-renderer-mark="true"></strong><a data-testid="link-with-safety" href="https://discuss.openedx.org/t/debugging-persistent-grade-issues/11155" title="https://discuss.openedx.org/t/debugging-persistent-grade-issues/11155" data-renderer-mark="true" class="cc-tgpl01"><strong data-renderer-mark="true">Debugging persistent grade issues</strong></a><span role="presentation" class="heading-anchor-wrapper"></span></h4>

* Presenter: @pdpinch 
* Notes: Dave Ormsbee (Axim) offered to connect with Peter Pinch  later to check on the issue. Last meeting, neither Peter or Dave were present in the meeting 
* Action items: Edward Zarecor will respond in the thread to ask if this is solved

**Comment by antoviaque** [comment]
* New information in the [forum thread](https://discuss.openedx.org/t/debugging-persistent-grade-issues/11155/8)
* @pdpinch _"would like help reviewing feedback on [PR 33963](https://github.com/openedx/edx-platform/pull/33963) which fixes a [bug found with persistent grades](https://discuss.openedx.org/t/debugging-persistent-grade-issues/11155)."_ (from [last core sprint retro](https://discuss.openedx.org/t/contributors-meetup-async-update-december-23rd-2023-january-5th-2024/12031/2#notebook_with_decorative_cover-summary-of-responses-3))

**Comment by e0d** [comment]
@jansenk from 2U has agreed to review the PR.

**Comment by itsjeyd** [comment]
@antoviaque My understanding from the most recent [meeting](https://openedx.atlassian.net/wiki/spaces/COMM/pages/4061102106/2024-02-15+Meeting+notes#%E2%8F%BA%EF%B8%8F-Transcript-and-Recording) of the Maintenance WG is that for edx-platform, right now it's fine to go to CCs for review by default.

> But ... [[this spreadsheet(https://docs.google.com/spreadsheets/d/1rMwbRldYwp-xPsAG2vijqwB__9M7P2AgjDxX31G7ucA/edit#gid=0)] is] the source of Truth moving forward for now and for [edx-]platform go to cc's first ...

As for which CC(s) would be in the best position to take the review based on their area of expertise, I'm not sure.

CC @feanil @mphilbrick211 @pdpinch

**Comment by itsjeyd** [comment]
@antoviaque Sounds good 🙂 

@bradenmacdonald Would you have bandwidth to review https://github.com/openedx/edx-platform/pull/33963, or a recommendation for another CC we could ask?

If not, we'll ping the arch-bom team.

CC @mphilbrick211

**Comment by bradenmacdonald** [comment]
@itsjeyd I have bandwidth but am not very knowledgeable around grading issues. Would be great if someone with more grading knowledge could review; if nobody is available I'm willing to take a stab at it.

**Comment by itsjeyd** [comment]
@bradenmacdonald OK, we'll see if we can [find another CC](https://discuss.openedx.org/t/contributors-meetup-async-update-february-3rd-february-16th-2024/12338/13) in the coming days.

CC @mphilbrick211

**Comment by ziafazal** [comment]
@itsjeyd I'm volunteering to review [PR](https://github.com/openedx/edx-platform/pull/33963). Could you please assign it to me?

**Comment by pdpinch** [comment]
Thank you @ziafazal!

**Comment by itsjeyd** [comment]
@ziafazal Of course, done! Thanks for volunteering.

**Comment by pdpinch** [comment]
After review by @ziafazal and changes from the author @asadali145, the [PR](https://github.com/openedx/edx-platform/pull/33963) has been merged! 

I'm optimistic this will fix the issue, but we'll have to do some testing after deployment to our QA and production environments.

**Comment by antoviaque** [comment]
@pdpinch This is great news! :) Glad to hear it. I'll mark this ticket as closed for now, but don't hesitate to reopen it if needed.
