### ISSUE TITLE
Sending strings from frontend-app-communications to Transifex

### ISSUE THREAD

**Issue by antoviaque** [openedx/wg-coordination#107]
Contributor meetup topic imported from https://openedx.atlassian.net/wiki/spaces/COMM/pages/3934289923/2023-11-28+CC+Working+Group+Meeting+Notes

**How do we make sure strings in frontend-app-communications are sent to Transifex?** 

* Presenter: @sambapete 
* Notes from previous meetings: 
   * Not fully discussed during the [previous meeting](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3885891585/2023-10-31+CC+Working+Group+Meeting+Notes#Follow-up---Open-edX-Survey-Report) as Pierre Mailhot was not present, but the [topic was brought up in Slack](https://openedx.slack.com/archives/C015KC8CN76/p1698722413888639?thread_ts=1698720437.500239&cid=C015KC8CN76).
  * There seemed to be a blocker on the availability of Atlas for Quince, but it now seem available: https://github.com/openedx/frontend-app-communications/pull/156
  * Strings are sent to Transifex, to the Open edX translation project, will be used by Atlas from Quince (maybe, as some of the changes were made after the cut for Quince). 
  * Is MFE translation support production ready? Yes, since Olive.
  * Not sure this has been tested by the BTR group. Not sure if it’s on the BTR backlog, but there is some issues items on the MFE projects
  * You have to translate in both the edx-platform and openedx projects, risks of sync issues between the two projects - question for David and Omar to know when Atlas will be put in place. Will require some setup to transition between the two.
  * For Pierre, not an issue for Quince for him, as he has a hack, but could be for anybody else not using English. This workaround could be communicated with others, but might require access to be granted by Eden & Omar.
  * Quality control issue about MFEs being put into production
* Action items:
  * @jalondonot  will be bringing it up with the BTR group and ask @OmarIthawi 
  * @sambapete  to see with the BTR group and @Peter Pinch about posting a warning about this in the release notes, and give a workarounds: use the JSON file of the translations, and use it with the feature in Tutor to override the language files

**Comment by antoviaque** [comment]
@OmarIthawi I don't know if there is another ticket for this bug already - @sambapete might be able to better answer that, since he brought up the issue for discussion.

**Comment by sambapete** [comment]
Unfortunately, because of upcoming changes in our organization to be
announced soon, I won't be able to follow up on this.

**Comment by sambapete** [comment]
One thing I might point out, and that might be the biggest problem right
now, is that not all translators have access to frontend-app-communications
strings in Transifex at this point thus making it difficult to use by
operators who didn't have access like I did for fr_CA. Unless this has
changed very recently but I haven't checked since early December 2023. I
agree with @Omar Al-Ithawi ***@***.***> that it might work for fr_CA
but maybe not for other languages because the strings have not been
translated yet.

**Comment by OmarIthawi** [comment]
Makes sense @sambapete. We'll not tag you again for this.

Hopefully, we get to work with you in another way.

Thanks again @sambapete for all of your hard work and contributions.

**Comment by antoviaque** [comment]
Thanks @sambapete - and sorry to see you go :(

@OmarIthawi does @sambapete 's answer help answering your question? We could treat the current ticket as the bug report.

**Comment by OmarIthawi** [comment]
The strings are already in Transifex, however most translators aren't using the project:

 - https://app.transifex.com/open-edx/openedx-translations/content/

We're cutting off the old project and we'll be using the new one, so it'll be good. I don't think this is a bug anymore but I'm happy to be shown a more specific bug report.

**Comment by antoviaque** [comment]
@OmarIthawi I'm not fully familiar with the issue so it's hard for me to answer, but I think I remember Pierre mentioning that few of the translators had access to the new Transifex project - do you know if that's still the case? And would all strings in all MFEs and all languages appear in the release if they are done there?

@ehuthmacher I think you are the chair of the  Translation working group, right? Do you know if there are outstanding issues on your side with MFE translations?

**Comment by jalondonot** [comment]
09/01 Contributor Meetup Update:
- @jalondonot will invite @ehuthmacher to the redwood.1 release planning session.

**Comment by antoviaque** [comment]
@ehuthmacher @OmarIthawi @brian-smith-tcril What would be required exactly to transition to the new project? Only provide access to all the current translators, or is there anything else? For providing access - do we have a list of all the translators who should be given access? And who has the right to do this?

**Comment by OmarIthawi** [comment]
Yes, the cutover has been decided and done. I think we should close this issue as done. Bug reports are welcome!

**Comment by antoviaque** [comment]
@OmarIthawi Great to hear! :+1:
