### ISSUE TITLE
Elephant factor increase

### ISSUE THREAD

**Issue by antoviaque** [openedx/wg-coordination#118]
This issue is to follow up on a topic from the contributor meetup working group

2U/edX is divesting from some of the maintenance due to layoffs (while remaining committed to maintain a significant part of the codebase), so this is going to affect the [elephant factor](https://chaoss.community/kb/metric-elephant-factor/). 

See:
* https://discuss.openedx.org/t/statement-concerning-the-latest-round-of-2u-layoffs/12243
* https://openedx.org/blog/edx-2u-update/

The reassignment of the work itself is managed by the maintenance working group and @feanil - but as discussed on the forum this is a good opportunity to improve and balance some of the historical distortions on governance due to a low elephant factor. This is a ticket to discuss these changes.

I have brought up some of those in the forum:

> Would some of the rules change? And would the existing rules be applied to all members equally now - for example, in regards to the requirement for maintainers to be core contributors?

> Another practice that could be improved would be to assign all commit rights through the core contributor nomination & review mechanism, vs being automatic when joining specific organizations - this way everyone would have the same incentives to become maintainers: to be able to decide on what gets into the official code base (by doing the work of maintaining it afterwards).

> To avoid removing existing merge rights, it could make sense to grandfather in existing permissions. But for new people or new employees joining the project, getting everyone to acquire merge rights like everyone else in the community, by becoming a core contributor or a maintainer. Everyone could still get permissions like before, but would have to go through the community process/training. If we are going to ask the community as a whole to step up our contribution to the project maintenance, putting ourselves on equal footing proportional to our contribution level would be a good way to align incentives.

CC @regisb

**Comment by jalondonot** [comment]
20/02 Contributors' Meetup Update:

- Aligned with edunext's proposal to maintain some repositories, they will begin nominating several core contributors this week.
- @jalondonot asks if, among the responsibilities that the maintainers currently have, the [proposal](https://openedx.atlassian.net/wiki/spaces/COMM/pages/4039770114/Redwood+Release+Testing+Strategy+Draft) launched by some members of the BTR and the Product WG to improve the Open edX release process is being considered. Although it is an ideal and we are not there yet, the list of responsibilities of a maintainer should be very clear and explicit. He'll reach out to the Maintenance WG to get their insight on this matter.
- @sarina raises the red flag about separating the responsibility of fixing the errors found during the release testing process from the person reporting them.

**Comment by antoviaque** [comment]
There have been a number of people and organization volunteering here, but I'm not completely clear on whether that's sufficient, so I have asked there: https://discuss.openedx.org/t/statement-concerning-the-latest-round-of-2u-layoffs/12243/10?u=antoviaque

**Comment by antoviaque** [comment]
There has just been a partner meeting about this, to focus the contributions of partners on maintenance: https://otter.ai/u/QyuMZ_sLsvShWD36ahfVkLGQgr8?view=transcript&tab=chat

Metric given during the meeting: we would need ~150 maintainers in total (not full times), for an equivalent in volume of work to 10-20 full time developers.

**Comment by jalondonot** [comment]
14/05 Contributors' meetup update:

- @e0d  suggested a scheme to classify repositories into three levels of complexity to better estimate the workload. He planned to discuss this with Feanil and assess the uptake from people offering support for main maintenance.

**Comment by antoviaque** [comment]
As discussed during the conference and the last contributors meetup, we have established that the elephant factor has now increased from 1 to 3 (or 4 by some accounts) - the main goal of the current ticket is now addressed, so I am going to close this ticket.

One follow-up element would be to track the elephant factor in the future, as well as other factors -- this would fit in #113 Community OKR, I am going to comment there.
