### ISSUE TITLE
Call for Help: Testing Coordinator wanted for Redwood release!

### ISSUE THREAD

**Issue by jalondonot** [openedx/wg-coordination#119]
The [BTR WG](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1022099494/Build-Test-Release+BTR+Working+Group) is looking to fill the following vacant positions in preparation for the [Redwood release](https://openedx.atlassian.net/wiki/spaces/COMM/pages/13205845/Open+edX+Release+Planning):

Release Testing Coordinator: The release testing coordinator ensures release candidates are tested before a tag is made. The coordinator does not necessarily have to run tests themselves, but they will coordinate testing in general. From Redwood, the Product WG will be involved in the testing process supporting the Testing Coordinator with this task.

As we will be cutting Redwood in approximately a month, we hope to fill these positions as soon as possible to begin preparations for the release testing process. Do not hesitate to contact me if you have any questions about the roles. As you know, this process is critical for the community and we require your support, which I thank you in advance.

**Comment by antoviaque** [comment]
Question: what is the difference between this role and the role from product and Jenna? Answer: the product working group establishes the testing plan, while the testing coordinator coordinates the execution of the tests, and represents the BTR working group with the product working group.

Peter Pinch has volunteered - also Adolfo originally. In the meeting, we were enthusiastic about @pdpinch 's candidature :)

Btw Redwood release is moved from the 9th to a bit later (TBD depending on what can be landed).

**Comment by jalondonot** [comment]
@pdpinch and Dean have accepted the role for Redwood :)
