### ISSUE TITLE
Release management retrospective - Redwood

### ISSUE THREAD

**Issue by antoviaque** [openedx/wg-coordination#125]
From the [May 24th core contributor retrospective](https://discuss.openedx.org/t/contributors-meetup-async-update-may-11th-may-24th-2024/13081/2#notebook_with_decorative_cover-summary-of-responses-3):

> After the Redwood Release, we need to review and reorganize the testing plan before the next release. (@pdpinch)

**Comment by jalondonot** [comment]
We held a first session on 29/07 and plan to finish the retrospective on 12/08. [Here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/4318527513/Redwood.1+Retrospective) is where we're tracking the activity.
