### ISSUE TITLE
Community-run Open edX CD

### ISSUE THREAD

**Issue by arbrandes** [openedx/wg-coordination#14]
Run a continuous deployment of Open edX as a way to catch problems with the [Native Installation](https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/1969455764/Koa+Native+Open+edX+platform+Ubuntu+20.04+64+bit+Installation).

Currently this is undertaken by OpenCraft, where `edx-platform@master` and `edx-platform@koa.master` are deployed periodically using  a subset of the `edx/configuration` playbooks run for the Native Installation, and notifications sent to [the open-edx-btr-notifications mailing list](https://groups.google.com/g/open-edx-btr-notifications/).

### Limitations

See #15.

**Comment by arbrandes** [comment]
@0x29a, do we also run this periodically for `open-release/koa.master`?

**Comment by 0x29a** [comment]
Yes, @arbrandes: https://periodic-build-koa.opencraft.hosting/.

**Comment by BbrSofiane** [comment]
The work done on openedx/build-test-release-wg#19 might be useful for this topic.

**Comment by arbrandes** [comment]
Since you're doing most of the work, here, I'm assigning you @BbrSofiane - hope you don't mind. :)

**Comment by nedbat** [comment]
We currently have three efforts: OpenCraft's existing CI, overhang.io's jobs running on GitLab, and @BbrSofiane's GitHub Actions. Is that right?

**Comment by BbrSofiane** [comment]
> Is that right?

Yes

**Comment by antoviaque** [comment]
I believe this is now handled a different way through custom deployments for each release, and sandboxes? I'm closing the ticket, but don't hesitate to reopen it if it is still useful.
