### ISSUE TITLE
Improve community-run Open edX CD

### ISSUE THREAD

**Issue by arbrandes** [openedx/wg-coordination#15]
During the koa.2 tagging process, [an issue was identified](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2373255193/RCA+koa.2) with the current `edx-platform@master` continuous deployment run by OpenCraft.  Essentially, the current process does not run through all the steps in the [Native Installation](https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/1969455764/Koa+Native+Open+edX+platform+Ubuntu+20.04+64+bit+Installation), which as of now is still the only officially supported method that can be used by the community.

The objective here is to find an alternative that _does_ run through all of the steps in the Native Installation so that any such failures can be caught.

**Comment by antoviaque** [comment]
@arbrandes Any suggestions on this? Would the potential move to Tutor + Docker provide an opportunity to improve this?

**Comment by arbrandes** [comment]
@antoviaque, for Lilac, I don't see a way for Ocim to do this in time (it assumes database servers will have been already provisioned).  If you feel OpenCraft should contribute something in this direction I can look into some simple automation to achieve it.  Basically:

* Fire up a suitably large VM every day
* Run the few commands specified in [the Native Installation](https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/1969455764/Koa+Native+Open+edX+platform+Ubuntu+20.04+64+bit+Installation) after bootup
* Check that the exit status is 0, and if not, send an email to the list

If not us, the maybe somebody in the group can step up.  @nizarmah, if there's enough time in the next meeting, can you bring attention to this, please?

**Comment by nizarmah** [comment]
@arbrandes Sure! 👍🏼 I'll make sure to bring it up if there's enough time!

**Comment by antoviaque** [comment]
@arbrandes Yup, it doesn't need to necessarily be for lilac, but this could be included in the requirements of the move of Ocim to containers, to make sure our solution then allows for this?

**Comment by arbrandes** [comment]
@antoviaque, alright, will do.

**Comment by antoviaque** [comment]
@arbrandes I believe this now has been completed, although in a different way through sandboxes, so I'm closing the ticket, but don't hesitate to reopen it if that's incorrect.
