### ISSUE TITLE
Organize the contributor's meetup

### ISSUE THREAD

**Issue by arbrandes** [openedx/wg-coordination#3]
https://discuss.openedx.org/t/open-edx-contributors-meetup/1450
https://openedx.atlassian.net/wiki/spaces/COMM/pages/1198719885/Contributors+Meetup

The meetup organizer is also tasked as [the board](https://github.com/openedx/community-wg/projects/1#card-55287233)'s triager.  (I.e., managing and refining the tasks on the board.)

**Comment by antoviaque** [comment]
@arbrandes Is the management & refinement of the current board included in this role? 

Btw, what are the rules/permissions for who can contribute to the tasks themselves? For example, assign them, or move them? I can't do this anymore with the new board for example. It could make sense to let people at least assign themselves to tasks, and move them through the different status?

CC @nasthagiri

**Comment by antoviaque** [comment]
@arbrandes Also, what about creating new tasks? I could for example create https://github.com/openedx/community-wg/issues/19 but it doesn't show up on the board. 

NB: There would also be a need to create tasks for each of the points from the agenda at https://github.com/openedx/community-wg/issues/18 currently missing as tasks on the board.

**Comment by antoviaque** [comment]
@arbrandes And last, a few tasks from the old Trello board that might be worth moving here too:
* https://trello.com/c/yFPFHaQR/66-contributor-t-shirt (of course)
* https://trello.com/c/gPfcC94G/108-mfe-theming-styling-oep

**Comment by arbrandes** [comment]
@antoviaque, good points.  I invited regular meeting attendees (past and present) that were not already [members of the openedx org](https://github.com/orgs/openedx/people) as triagers.  This will let them do as you suggest.

As for creating new tasks on the board, once created, one has to put them on the "Main" board under the "Projects" heading to the right of the issue description.

I tried to create the remaining issues, but if I missed any, any group participant should now be able to do so.

**Comment by antoviaque** [comment]
@arbrandes Thank you for creating the tasks!

> yes, the meetup organizer is (at least provisionally) tasked with managing the board. :)

You mean that there is no solution to allow everyone to move their own tasks through statuses? It feel like a permission issue that really needs solving, it doesn't encourage ownership of tasks.

**Comment by arbrandes** [comment]
@antoviaque, ah, no, everybody should have triaging rights, by now.  They'll be able to move their issues along by themselves.

**Comment by antoviaque** [comment]
@arbrandes Perfect then! :) Thank you for taking care of this.

**Comment by antoviaque** [comment]
This is now being organized regularly, and this ticket isn't being used for tracking anymore, so closing it.
