### ISSUE TITLE
Core contributors sprints - Discovery

### ISSUE THREAD

**Issue by antoviaque** [openedx/wg-coordination#43]
Discuss establishing sprints for core contributors, to follow and prioritize better the 20h+/month/contributor of committed work.

To bring up:
* Is this a good idea?
* Sprint length (2 weeks?)
* Sprint planning meeting (contributors meetup?)
  * Attendance from all core contributors? Or their group chair for core contributors belonging to a specific working group (scrum of scrum, with sprint planning done at the core contributor level?)
* Sprint board (community-wg board?)

See also https://github.com/edx/open-edx-proposals/issues/229

**Comment by sarina** [comment]
@antoviaque I think this is a really good idea (if I'm understanding the problem we want to solve correctly), but one that leaves me scratching my head about how to implement it. The problem I think we're solving for is making us, as CCs, feel more cohesive and having a better understanding of what one another is working on. And then from that, join forces to get very meaningful work done more quickly. From my side I'd benefit to see where we have holes in CC coverage of repos, where delays are happening, and head off CC frustration earlier on.

I like what we do on the CE team, where we're all pretty senior and working on disparate things - we do a 15m planning meeting where we discuss what we're working on next sprint and get feedback/input from the team, and ask for help if we'll need it. For now this model could work for CCs - perhaps 2 synchronous short planning meetings (for two halves of the globe), and use either the WG board or even a simple shared document to track. I think that this, or another, very lightweight process could help solve the problems would be a good first iteration. I hesitate to put anything more heavyweight on peoples' plates.

😅 that was a long set of thoughts! Any on your end?

**Comment by antoviaque** [comment]
This has been implemented for some time, and a new iteration is being worked on in https://github.com/openedx/wg-coordination/issues/95 so closing this ticket.
