### ISSUE TITLE
Hook based extensions proposal

### ISSUE THREAD

**Issue by arbrandes** [openedx/wg-coordination#5]
@felipemontoya proposes:

https://docs.google.com/document/d/1jhnudz6AVtVt0ZSRSwOwj9gJ0lsDDn_8mUCPehLPzLw/edit#heading=h.vo2ywbxdhh5

[(Original issue)](https://trello.com/c/BCJpY06R)

**Comment by arbrandes** [comment]
@feanil is taking on the review of this from the edX side.

**Comment by felipemontoya** [comment]
This also has a OEP now (https://github.com/edx/open-edx-proposals/pull/184)

**Comment by antoviaque** [comment]
@arbrandes Shoulds this thus be assigned to @felipemontoya ?

**Comment by felipemontoya** [comment]
I can take the assignment. Does this mean I should be reporting updates here?

**Comment by arbrandes** [comment]
@felipemontoya, if you could, that would be great.  It would make the meetup that much quicker. :)

**Comment by nizarmah** [comment]
Hello @felipemontoya! I was wondering if you're still searching for an Arbiter, and if there's any chance I can help with that. Let me know please! 😃

**Comment by felipemontoya** [comment]
@nizarmah thanks a lot! That would be great.
I had informally talked with @bradenmacdonald over a coffee break about him being the arbiter. I guess you guys are in close contact. Let me know if you have any preference and I'll update the OEP PR. I should have updated with the latest feedback a few days ago. I'm late there.

**Comment by nizarmah** [comment]
@felipemontoya sorry, I ended up missing this notification completely. I thought I'd reply and mention that this was addressed in the [OEP pull request](https://github.com/edx/open-edx-proposals/pull/184#issuecomment-806365738) so that the necessary context is there 👍🏼

**Comment by antoviaque** [comment]
This has been adopted and implemented, so closing the ticket.
