### ISSUE TITLE
Review Open edX Roadmap

### ISSUE THREAD

**Issue by arbrandes** [openedx/wg-coordination#6]
The community should review the [Open edX Roadmap](https://openedx.atlassian.net/secure/RapidBoard.jspa?rapidView=657&projectKey=OEROADMAP)

**Comment by antoviaque** [comment]
@nasthagiri @e0d Do we intend to continue the work started with the roadmap? What would be the next steps on this?

PS: Your names don't seem to autocomplete on this org - is there a way to allow that?

**Comment by antoviaque** [comment]
It has been in place for some time, and reviewed, so I'm closing this ticket. Though if another round of reviews would be useful, this can be reopened, or a brand new ticket created.
