### ISSUE TITLE
Talk proposal reviews

### ISSUE THREAD

**Issue by antoviaque** [openedx/wg-coordination#86]
This is being done by selected reviewers in Sessionize - each reviewer sorts a series of talk proposals, and Sessionize sums it up to select the favorite ones.

**Comment by antoviaque** [comment]
Not sure if / where there is already a ticket about talks proposals reviews for the conference, so creating this one to reference the work. 

@feanil you might know, since you have been the one emailing us reviewers :)

**Comment by feanil** [comment]
Thanks @antoviaque I had not created a previous one so this one works great.  Is the expectations that CCs that want to track this as a part of their time should just add themselves as assignees on this ticket?

**Comment by antoviaque** [comment]
@feanil Thanks! Yup, though imho it's not necessary to be assigned to a ticket to log time spent on it -- but this way there is a ticket to reference for CC work scope. And those who didn't participate to the reviews can also know those happened :)
